2022-11-14 09:15:20,188 - INFO - Bot start
2022-11-14 09:15:20,190 - INFO - Scheduler started
2022-11-14 09:15:20,196 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x00000204C6896410>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /bot5668214541:AAFoa7JzrDib1aD0SM0C2al4J_GsxK6gbYU/getMe
2022-11-14 09:15:20,197 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x00000204C6896530>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /bot5668214541:AAFoa7JzrDib1aD0SM0C2al4J_GsxK6gbYU/getMe
2022-11-14 09:15:20,197 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x00000204C6896680>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /bot5668214541:AAFoa7JzrDib1aD0SM0C2al4J_GsxK6gbYU/getMe
2022-11-14 09:16:51,974 - INFO - Bot start
2022-11-14 09:16:51,975 - INFO - Scheduler started
2022-11-14 09:17:04,012 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000002D58C516410>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /bot5668214541:AAFoa7JzrDib1aD0SM0C2al4J_GsxK6gbYU/getMe
2022-11-14 09:17:04,013 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000002D58C516530>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /bot5668214541:AAFoa7JzrDib1aD0SM0C2al4J_GsxK6gbYU/getMe
2022-11-14 09:17:04,013 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000002D58C516680>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /bot5668214541:AAFoa7JzrDib1aD0SM0C2al4J_GsxK6gbYU/getMe
2022-11-14 09:17:42,050 - INFO - Bot start
2022-11-14 09:17:42,052 - INFO - Scheduler started
2022-11-14 09:23:14,491 - INFO - Received signal 2 (SIGINT), stopping...
2022-11-14 09:23:14,491 - INFO - Scheduler has been shut down
2022-11-14 09:23:21,329 - INFO - Bot start
2022-11-14 09:23:21,330 - INFO - Scheduler started
